apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: eyego-task
type: Opaque
data:
  # MongoDB credentials (base64 encoded)
  # Username: admin (base64: YWRtaW4=)
  # Password: admin123 (base64: YWRtaW4xMjM=)
  MONGO_USERNAME: YWRtaW4=
  MONGO_PASSWORD: YWRtaW4xMjM=
  # MongoDB URI (base64 encoded)
  # mongodb://admin:admin123@mongodb-service:27017/eyego?authSource=admin
  MONGO_URI: bW9uZ29kYjovL2FkbWluOmFkbWluMTIzQG1vbmdvZGItc2VydmljZToyNzAxNy9leWVnbz9hdXRoU291cmNlPWFkbWlu
