apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eyego-ingress
  namespace: eyego-task
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: eyego-task.local
    http:
      paths:
      - path: /producer
        pathType: Prefix
        backend:
          service:
            name: producer-service
            port:
              number: 3000
      - path: /consumer
        pathType: Prefix
        backend:
          service:
            name: consumer-service
            port:
              number: 3001
