apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-config
  namespace: eyego-task
data:
  PORT: "3001"
  NODE_ENV: "production"
  KAFKA_BROKERS: "kafka-0.kafka-service.eyego-task.svc.cluster.local:9092"
